### ISSUE TITLE
Webserver not working

### ISSUE THREAD

**Issue by ramesh8v** [aursiber/MareyMap#1]
Hello, 
I'm trying to use the MareyMap web server (http://lbbe-shiny.univ-lyon1.fr/MareyMapOnline/), but the service doesn't seem to work. At step 1, when I selected data from pulldown menu, it's saying "Disconnected from the server". Even after reloading multiple times, the service doesn't seem to work. I appreciate any help. 

Thanks,
Ramesh

**Comment by aursiber** [comment]
I am going to take a closer look. Cheers.

**Comment by aursiber** [comment]
It seems to be working again. Can you try it?
