### ISSUE TITLE
Select multiple points at once

### ISSUE THREAD

**Issue by coolkom** [aursiber/MareyMap#2]
Hello,

Would it be possible to make it feasible to select multiple points to be removed at once by dragging the cursor over them, instead of selecting point by point, which really painfull in case of thousands of markers?
Thanks.

**Comment by aursiber** [comment]
Hi, 
Sorry, but we do not wish to develop this feature.
The interactive point deletion function is only available for a fine, precise and restricted selection of points.
To delete a large set of points, we advise you to modify your dataset beforehand by setting the value of the `vld` column to `FALSE`.
Best regards.
